@TmsApi_HostAddress = http://localhost:5238

GET {{TmsApi_HostAddress}}/weatherforecast/
Accept: application/json

###

### Create a New Enrollment
POST http://localhost:5238/api/enrollments
Content-Type: application/json

{
    "studentId": "STU-8821",
    "courseCode": "CS-301"
}

### GET an Existing Enrollment (Should return 204)
GET {{TmsApi_HostAddress}}/api/enrollments/9b0592c4

### Delete an Existing Enrollment (Should return 204)
DELETE {{TmsApi_HostAddress}}/api/enrollments/05de14ea

### Delete a Non-Existent Enrollment (Should return 404)
DELETE {{TmsApi_HostAddress}}/api/enrollments/does-not-exist



### Test Exercise 6: Intentionally Crash the API (500)
GET {{TmsApi_HostAddress}}/api/error

### Test Exercise 6: Empty Status Code Translation (404)
GET {{TmsApi_HostAddress}}/api/missing-page



### POST Student request #####################

POST http://localhost:5238/api/students
Content-Type: application/json

{
  "name": "Dawit",
  "age": 23,
  "gpa": 3.7
}

### GET Student request #####################

GET {{TmsApi_HostAddress}}/api/students
X-Training-User: Admin

### Delete a Student
DELETE http://localhost:5238/api/students/11



##########Course CRUD##########

### 1. Create a Course (POST)
POST {{TmsApi_HostAddress}}/api/courses
X-Training-User: Admin
Content-Type: application/json

{
  "code": "CSE-102",
  "title": "Introduction to Computer Science",
  "maxCapacity": 25,
  "enrollments": []
}

### 2. Get All Courses (GET)
GET {{TmsApi_HostAddress}}/api/courses
X-Training-User: Admin

### Get a Course by ID
GET {{TmsApi_HostAddress}}/api/courses/13
X-Training-User: Admin

### 4. Delete a Course (DELETE)
DELETE {{TmsApi_HostAddress}}/api/courses/80
X-Training-User: Admin